{
  save_every: -1,
  save_path : './results/replica_test/',
  dump_kfs: False,
  dataset: {
    type: 'replica',
    path: './datasets/replica/vMAP_rerender/',
    source_id: 1250,
    target_id: 1260,
    start_id: 0,
  },
  frontend: {
    downsample_pow: 2,

    normals_scannet: True,
    sam_path: './models/sam_vit_h_4b8939.pth',
    normals_path: './models/scannet.pth',
    num_pts: 300,
    num_pts_active: 100,
    include_normals: False,

    normals: {
      integrator: 'tiled',
      integration_shape: [240, 320],
      network_dim: [480, 640],
    },

    cg_max_iter: 1000,
    cg_tol: !!float 1e-3,

    check_for_depth_disc: True,

    depth_disc_params: {
      filter_size: 3,
      depth_threshold: !!float 0.1,
      area_keep_ratio: !!float 1e-3,
    }
  },
  sam_params: {
    # infer_resolution: [768, 1024],
    infer_resolution: [960, 1280],
    select_smallest: True,

    nms: True,
    box_nms_thresh: !!float 0.8,

    iou_threshold: !!float 0.0,
    stability_threshold: !!float 0.90,
    filter_edge_points: True,
    
    cut_masks_by_edges: False,
    edge_probs_threshold: 0.1,
  
    filter_by_box_size: False,
  },
  aligment: {
    cost_params: {
      normal_loss: 'leclerc',
      normal_weight: !!float 0.0,
      depth_median_weight: !!float 0.0,
    },

    mono_init: True,
    # pyramid_preprocess: 2,
    pyramid_min: 0,
    pyramid_max: 4,        
  },
  vis: {
    mono_align: True,
    pts_show_every: 2,
  },
  paused: False,
}